name: GLaDOS 自动签到

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: read

jobs:
  checkin:
    runs-on: ubuntu-latest

    steps:
      - name: 获取项目代码
        uses: actions/checkout@v4

      - name: 安装 Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装依赖
        run: pip install requests

      - name: 执行签到
        env:
          GLADOS_COOKIE: ${{ secrets.GLADOS_COOKIE }}
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        run: python glados.py
